##########################################################################
##  LOCAL Development setup                                             ##
##                                                                      ##
##  Use with :                                                          ##
##  jekyll build --config _config.yml,_config_dev.yml,_config_local.yml ##
##########################################################################

url: http://localhost:4000/

protocol: http
host: localhost
port: 4000

