language:               en
title:                  "Pavement Preservation"
description:            "Resource for Practicing Professionals"
google-verification:    ""

# source:      .
# destination: ./_site
# plugins:     ./_plugins
# layouts:     ./_layouts
include:
  - .nojekyll
              ]
# exclude from the conversion and from sitemap.xml
exclude:
 - README.md
 - Gemfile
 - Gemfile.lock
 - Rakefile
 - vendor

# keep_files:  ['.git','.svn']

plugins:
 - jekyll-sitemap
 - jekyll-paginate

timezone:    America/New_York
# encoding:    nil

# future:      true
# show_drafts: false
# limit_posts: 0
# highlighter: pygments

paginate_path: '/news/page:num'
paginate:      5

# markdown:      kramdown
# markdown_ext:  markdown,mkdown,mkdn,mkd,md

excerpt_separator: "<!--more-->"

# url: ""
baseurl: ""

kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   use_coderay: false
    parse_block_html: true
    parse_span_html: true
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# redcloth:
#   hard_breaks: true

permalink: pretty


############### RELATED ARTICLES ####################
# if set to true print a list of related articles
# on collection's articles
printRelatedArticles: true

# maximum number of related articles searched in each collection
maxRelated : 5
# minimum number of tag match to be a related
minTagMatch: 4
############### COLLECTIONS ####################
collections:

  methods:
    output: true   # every page in the collection will be created
    isKB: true     # is part of Knowledge base
    name: "Methods" # Print name used in titles, menus, ...
    categories:
      - { name: "Fog Seals", slug: "fog-seals" }
      - { name: "Chip Seals", slug: "chip-seals" }
      - { name: "Spray Seals", slug: "spray-seals" }
      - { name: "Microsurfacing & Slurry", slug: "microsurfacing-and-slurry" }
      - { name: "Combination Seals", slug: "combination-seals" }
      - { name: "Cold-Mix Asphalt", slug: "cold-mix-asphalt" }
      - { name: "Warm-Mix Asphalt", slug: "warm-mix-asphalt" }
      - { name: "Asphalt Overlays", slug: "asphalt-overlays" }
      - { name: "Recycling - Plant", slug: "recycling-plant" }
      - { name: "Recycling - In-Place", slug: "recycling-in-place" }
      - { name: "Crack & Joint Treatments", slug: "crack-joint-treatments" }
      - { name: "Concrete Overlays", slug: "concrete-overlays" }
      - { name: "Concrete Treatment", slug: "concrete-treatment" }
      - { name: "Patching & Preparation", slug: "patching-preparation" }
      - { name: "Milling & Grinding", slug: "milling-and-grinding" }

  materials:
    output: true
    isKB: true
    name: Materials
    categories:
      - { name: "Aggregates", slug: "aggregates" }
      - { name: "Asphalt Emulsions", slug: "asphalt-emulsions" }
      - { name: "Modified Emulsions", slug: "modified-emulsions" }
      - { name: "Rejuvenators and Recycling Agents", slug: "rejuvenators-and-recycling-agents" }
      - { name: "Asphalt Binders", slug: "asphalt-binders" }
      - { name: "Modified Binders", slug: "modified-binders" }
      - { name: "Asphalt Modification", slug: "asphalt-modification" }
      - { name: "GTR", slug: "gtr" }
      - { name: "Polymers", slug: "polymers" }
      - { name: "Moisture Damage Control", slug: "moisture-damage-control" }
      - { name: "Asphalt Additives", slug: "asphalt-additives" }
      - { name: "Mixture Additives", slug: "mixture-additives" }
      - { name: "Fibers", slug: "fibers" }
      - { name: "RAP", slug: "rap" }
      - { name: "RAS", slug: "ras" }
      - { name: "Other Recycled Materials", slug: "other-recycled-materials" }
      - { name: "Cement", slug: "cement" }
      - { name: "Concrete Additives", slug: "concrete-additives" }

  manage:
    output: true
    isKB: true
    name: Manage
    categories:
      - { name: "Safety", slug: "safety" }
      - { name: "Policy", slug: "policy" }
      - { name: "Strategy", slug: "strategy" }
      - { name: "Pavement Management Systems", slug: "pavement-management-systems" }
      - { name: "Specifications", slug: "specifications" }
      - { name: "Tests", slug: "tests" }
      - { name: "Quality Control & Assurance", slug: "quality-control-assurance" }
      - { name: "Research", slug: "research" }
      - { name: "Life Cycle Cost Analysis", slug: "life-cycle-cost-analysis" }
      - { name: "Data Management", slug: "data-management" }
      - { name: "Training", slug: "training" }

# this array determine article's types and order
# a collection article with non matching type will not be listed
# article must be tagged with a type.slug
# eg : "type: article" or "type: research"

articleTypes :
  - { name: "Article", plural: "Articles", slug: "article", icon: "fi-page" }
  - { name: "Video", plural: "Videos", slug: "video", icon: "fi-video" }
  - { name: "Link", plural: "Links", slug: "link", icon: "fi-link" }
  - { name: "Project", plural: "Projects", slug: "project", icon: "fi-page-search" }
  - { name: "Research", plural: "Research", slug: "research", icon: "fi-compass" }

############### DEFAULT CONFIGURATION ####################
defaults:

  - { scope: { type: "posts" }, values: { permalink: "/news/:year/:title/" } }


  - { scope: { type: "pages" }, values: { layout: "default" } }

  # default layout for collections articles
  - { scope: { type: "methods" }, values: { layout: "collection" } }
  - { scope: { type: "materials" }, values: { layout: "collection" } }
  - { scope: { type: "manage" }, values: { layout: "collection" } }


