language:            en
title:               "Pavement Preservation"
title_html:          "Pavement Preservation (P<sup>2</sup>)"

description:            "Resource for Practicing Professionals"
google-verification:    ""

# source:      .
# destination: ./_site
# plugins:     ./_plugins
# layouts:     ./_layouts
include:
  - .nojekyll
              ]
# exclude from the conversion and from sitemap.xml
exclude:
 - README.md
 - Gemfile
 - Gemfile.lock
 - Rakefile
 - vendor
 - .sass-cache
 - .idea

plugins:
 - jekyll-sitemap
 - jekyll-paginate-v2

timezone:    America/New_York
# encoding:    nil

# future:      true
# show_drafts: false
# limit_posts: 0
# highlighter: pygments

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 2

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################



# markdown:      kramdown
# markdown_ext:  markdown,mkdown,mkdn,mkd,md

excerpt_separator: "<!--more-->"

# url: ""
baseurl: ""

kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   use_coderay: false
    parse_block_html: true
    parse_span_html: true
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# redcloth:
#   hard_breaks: true

permalink: pretty

sass:
  # loading path from site root
  # default to _sass
  # sass_dir: node_modules/bootstrap/scss

  # multiple load paths
  # doesn't work in safe mode (github pages)
  load_paths:
    - assets
    - node_modules

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: nested


## new in 2.8
liquid:
  strict_variables: false # default: false
  strict_filters: true # default: false
  error_mode: strict # default: warn

############### RELATED ARTICLES ####################
# see _pligins/hook-related-article.rb

# maximum number of related articles searched in each collection
maxRelated : 5
# minimum number of tag match to be a related
minTagMatch: 1


############### COLLECTIONS ####################
collections:

  methods:
    output: true   # every page in the collection will be created
    isKB: true     # is part of Knowledge base
    name: "Methods" # Print name used in titles, menus, ...

  materials:
    output: true
    isKB: true
    name: Materials

  manage:
    output: true
    isKB: true
    name: Manage

  documentation:
    output: true

# this array determine article's types and order
# a collection article with non matching type will not be listed
# article must be tagged with a type.slug
# eg : "type: article" or "type: research"

articleTypes :
  - { name: "Article", plural: "Articles", slug: "article", icon: "fi-page" }
  - { name: "Video", plural: "Videos", slug: "video", icon: "fi-video" }
  - { name: "Link", plural: "Links", slug: "link", icon: "fi-link" }
  - { name: "Project", plural: "Projects", slug: "project", icon: "fi-page-search" }
  - { name: "Research", plural: "Research", slug: "research", icon: "fi-compass" }

############### DEFAULT CONFIGURATION ####################
defaults:
  - { scope: { type: "posts" }, values: { permalink: "/news/:year/:title/", layout: "post" } }
  - { scope: { type: "pages" }, values: { layout: "default" } }
  - { scope: { type: "documentation" }, values: { layout: "documentation" } }
  # default layout for collections articles
  - { scope: { type: "methods" }, values: { layout: "collection" } }
  - { scope: { type: "materials" }, values: { layout: "collection" } }
  - { scope: { type: "manage" }, values: { layout: "collection" } }

############### Algolia jekyll plugin configuration ####################

algolia:
  application_id: 'K3NGJZEZ95'
  search_only_api_key: '66a4234e97f1002b75f7eb36ed40eee7'
  index_name: 'p218'

  files_to_exclude:
    - manage/*/index.html
    - materials/*/index.html
    - methods/*/index.html*
    - documentation/**
    - faq/**
    - legal/**
    - pages/**

  # nodes_to_index: 'p,.summary'

############### Jekyll built-in profiler ####################
# this is an alternative to
#  `jekyll build --profile`
profile: false

############### custom DEBUG Widgets ####################

#### Commented includes tag (_plugins/tag-commented-include.rb)
#
# Wile digging into jekyll's code, it's not always easy to spot
# where code comes from.
# Commenting start and end for an include, helps a lot.
# Use :
# {% inc path/filename.ext param='value' param2='value' %}
comment_includes: true

#### Debug site variables
#
# If set to true, will output site variables
#
# variables present in **site_vars_NOT_to_print** array
# will not be printed

debug: true # deprecated

debug_breakpoints : true

debug_site_vars: true

site_vars_NOT_to_print:
# - config
# - data
# - time
# - tags
 - pages
 - posts
 - static_files
 - documents
# - categories
 - collections
 - html_pages
# - source
# - destination
# - plugins_dir
# - layouts_dir
# - data_dir
# - includes_dir
# - safe
# - include
# - exclude
# - keep_files
# - encoding
# - markdown_ext
# - strict_front_matter
# - show_drafts
# - limit_posts
# - future
# - unpublished
# - whitelist
# - plugins
# - markdown
# - highlighter
# - lsi
# - excerpt_separator
# - incremental
# - detach
# - port
# - host
# - baseurl
# - show_dir_listing
# - permalink
# - paginate_path
# - timezone
# - quiet
# - verbose
# - defaults
# - liquid
# - rdiscount
# - redcarpet
# - kramdown
# - title
# - email
# - description
# - url
# - twitter_username
# - github_username
# - sass
# - show_debug
# - site_vars_to_print
# - serving
# - watch
 - related_posts

#### Debug page variables
#
# If set to true, will output page variables
#
# variables present in **page_vars_NOT_to_print** array
# will not be printed
debug_page_vars: true

page_vars_NOT_to_print:
  - next
  - previous
#  - path
  - output
#  - url
  - content
#  - relative_path
#  - id
#  - collection
  - excerpt
#  - draft
#  - categories
#  - category
#  - layout
#  - title
#  - author
#  - date
#  - date_added_kb
#  - slug
#  - ext
  - related

############### Collection Category from Path Hook configuration ####################
CollectionCatFromPath:
  debug: false
