language:            en
title:               "Pavement Preservation"
title_html:          "Pavement Preservation"

description:         "Resource for Pavement Preservation Practicing Professionals"

timezone:    America/New_York

default_author: "P2 editors"


google-verification:    ""

include:
  - .nojekyll
              ]
# exclude from the conversion and from sitemap.xml
exclude:
 - README.md
 - Gemfile
 - Gemfile.lock
 - Rakefile
 - vendor
 - .sass-cache
 - .idea

plugins:
 - jekyll-sitemap
 - jekyll-paginate-v2



excerpt_separator: "<!--more-->"

# url: ""
baseurl: ""

kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   use_coderay: false
    parse_block_html: true
    parse_span_html: true
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# redcloth:
#   hard_breaks: true

permalink: pretty

sass:
  # loading path from site root
  # default to _sass
  # sass_dir: node_modules/bootstrap/scss

  # multiple load paths
  # doesn't work in safe mode (github pages)
  load_paths:
    - assets
    - node_modules

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: compressed


## new in 2.8
liquid:
  strict_variables: false # default: false
  strict_filters: false # default: false
  error_mode: strict # default: warn

############################################################
# Site configuration for the Jekyll Pagination V2 Gem
# see https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 2

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################
# automatic page creation configuration
# see https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md
autopages:
  enabled: true

  categories:
    enabled: true
    title:   "category : :cat"
    layouts:
      - kb_autopage_manage_collection_categories.html
      - kb_autopage_materials_collection_categories.html
      - kb_autopage_methods_collection_categories.html
    slugify:
      mode: 'ascii'
      cased: true

  tags:
    enabled: false
    title:   "tag : :tag"
    layouts:
      - kb_autopage_collections_tags.html
    slugify:
      mode: 'ascii'
      cased: true

  collections:
    enabled: true
    layouts:
      - 'kb_autopage_collection.html'
    title: 'Posts in collection :coll' # :coll
    permalink: '/kb/:coll'

############################################################

############### RELATED ARTICLES ####################
# see _pligins/hook-related-article.rb

# maximum number of related articles searched in each collection
maxRelated : 5
# minimum number of tag match to be a related
minTagMatch: 1


############### COLLECTIONS ####################
collections:

  methods:
    output: true   # every page in the collection will be created
    isKB: true     # is part of Knowledge base
    name: "Methods" # Print name used in titles, menus, ...
    permalink: "/kb/:collection/:path/"
  materials:
    output: true
    isKB: true
    name: Materials
    permalink: "/kb/:collection/:path/"
  manage:
    output: true
    isKB: true
    name: Manage
    permalink: "/kb/:collection/:path/"

  documentation:
    output: true

  events:
    output: false

############### DEFAULT CONFIGURATION ####################
defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/news/:year/:title/"
      layout: "post"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "documentation"
    values:
      layout: "documentation"
  -
    scope:
      path: "admin"
    values:
      layout: null

  # default layout for collections articles
  -
    scope:
      type: "methods"
    values:
      layout: "kb_collection_item"
  -
    scope:
      type: "materials"
    values:
      layout: "kb_collection_item"
  -
    scope:
      type: "manage"
    values:
      layout: "kb_collection_item"

############### Algolia jekyll plugin configuration ####################

algolia:
  application_id: 'K3NGJZEZ95'
  search_only_api_key: '66a4234e97f1002b75f7eb36ed40eee7'
  index_name: 'p218'

  settings:
    searchableAttributes:
      - title
      - unordered(content)
      - author
#      - category
#      - tags

  files_to_exclude:
    - _documentation/*
    - news/*
    - pages/**/*
    - pages/*

###########################################
#  All debugs are disabled for production #
#  DO NOT EDIT HERE !!!                   #
#  Edit in _config_dev.yml                #
###########################################

profile: false

verbose: false

comment_includes: true

debug_hooks: false

debug_breakpoints: false

debug_site_vars: false

debug_page_vars: false

CollectionCatFromPath:
  debug: false
