# Netlify build & deploy setup
# see https://www.netlify.com/docs/netlify-toml-reference/

[Settings]
ID = "p218"

[build]
  publish = "_site"
  command = "jekyll build && jekyll algolia"

[context.production]
   command = "jekyll build && jekyll algolia"
   environment = { JEKYLL_LOG_LEVEL = "info", JEKYLL_ENV = "production" }

[context.branch-deploy]
  command = "jekyll build --config _config.yml,_config_dev.yml && jekyll algolia"
  #command = "jekyll build && jekyll algolia"

#  environment = { JEKYLL_LOG_LEVEL = "debug", JEKYLL_ENV = "development" }
  environment = { JEKYLL_LOG_LEVEL = "info", JEKYLL_ENV = "production" }
