- host: AASHTO
  host_name: American Association of State Highway and Transportation Officials
  events_page: https://meetings.transportation.org/overview/
  website: https://www.transportation.org/

- host: AEMA
  host_name: Asphalt Emulsion Manufacturers Association
  events_page:
  website: https://www.aema.org/

- host: AMAP
  host_name: Association of Modified Asphalt Producers 
  events_page: https://modifiedasphalt.org/annual-conference/
  website: http://modifiedasphalt.org/

- host: APWA
  host_name: American Public Works Association
  events_page: https://www.apwa.net/MYAPWA/Events/MyApwa/Apwa_Public/Education_and_Events/Education_and_Events.aspx?hkey=1d367d0b-926e-4090-bde4-adfa4905de49
  website: https://www.apwa.net/

- host: ARRA
  host_name: Asphalt Recycling & Reclaiming Association
  events_page:
  website: https://www.arra.org/

- host: AI
  host_name: Asphalt Institute
  events_page: http://www.asphaltinstitute.org/training/
  website: http://www.asphaltinstitute.org/

- host: ASTM
  host_name: ASTM International
  events_page: https://www.astm.org/MEETINGS/filtrexx40.cgi?+-P+TERM+D04+searchresults.frm
  website: https://www.astm.org/COMMITTEE/D04.htm

- host: CONEXPO-CON/AGG
  host_name: CONEXPO-CON/AGG
  events_page:
  website: https://www.conexpoconagg.com/

- host: WOA
  host_name: World of Asphalt
  events_page:
  website: https://www.worldofasphalt.com/

- host: ISSA
  host_name: International Slurry Surfacing Association
  events_page:
  website: https://www.slurry.org/

- host: NACE
  host_name: National Association of County Engineers
  events_page: https://www.countyengineers.org/nace-annual-meetings
  website: https://www.countyengineers.org/

- host: NAPA
  host_name: National Asphalt Paving Association
  events_page: http://www.asphaltpavement.org/index.php?option=com_content&view=article&id=195&Itemid=322
  website: http://www.asphaltpavement.org/

- host: NCPP
  host_name: National Center for Pavement Preservation
  events_page: https://www.pavementpreservation.org/ncpp-hosted-conferences-meetings/
  website: https://www.pavementpreservation.org/

- host: SEPPP
  host_name: Southeast Pavement Preservation Partnership
  events_page: 
  website: https://tsp2pavement.pavementpreservation.org/southeast-seppp/

- host: RMWPPP
  host_name: Rocky Mountain West Pavement Preservation Partnership
  events_page: 
  website: https://tsp2pavement.pavementpreservation.org/rocky-mountain-west-rmwppp/

- host: NEPPP
  host_name: Northeast Pavement Preservation Partnership
  events_page: 
  website: https://tsp2pavement.pavementpreservation.org/northeast-neppp/

- host: MWPPP
  host_name: Midwestern Pavement Preservation Partnership
  events_page: 
  website: https://tsp2pavement.pavementpreservation.org/midwestern-mppp/

- host: TRB
  host_name: Transportation Research Board
  events_page: http://www.trb.org/AnnualMeeting/AnnualMeeting.aspx
  website: http://www.trb.org/Main/Home.aspx

- host: SEAUPG
  host_name: Southeastern Asphalt User/Producer Group
  events_page: http://seaupg.org/events-current.shtml
  website: http://seaupg.org/

- host: NEAUPG
  host_name: Northeast Asphalt User/Producer Group
  events_page: http://www.neaupg.uconn.edu/meetingsevents
  website: http://www.neaupg.uconn.edu/

- host: NCAUPG
  host_name: North Central Asphalt User Producer Group
  events_page: https://engineering.purdue.edu/~ncaupg/Activities/NCAUPG%20Activities.html
  website: https://engineering.purdue.edu/~ncaupg/

- host: RMAUPG
  host_name: Rocky Mountain Asphalt User/Producer Group
  events_page: http://www.rockymountainasphalt.com/meetings.html
  website: http://www.rockymountainasphalt.com/

- host: NBAUPG
  host_name: New Brunswick Asphalt User Producer Group
  events_page: https://www.nbupg.com/annual-seminar
  website: https://www.nbupg.com/

- host: NSUPA
  host_name: Nova Scotia User Producer Association
  events_page: 
  website: https://nsupa.ca/

- host: PCCAS
  host_name: Pacific Coast Conference on Asphalt Specifications
  events_page: http://pccas.org/meetings.html
  website: http://pccas.org/index.html

- host: NESMEA
  host_name: Northeastern States Materials Engineers Association
  events_page: http://www.nesmea.uconn.edu/upcoming-events
  website: http://www.nesmea.uconn.edu/

- host: NCAT
  host_name: National Center for Asphalt Technology
  events_page: 
  website: http://eng.auburn.edu/research/centers/ncat/

