---
#################################################################
#### Netlify cms configuration
#### see : https://www.netlifycms.org/docs/configuration-options/
#################################################################
# leave this front matter, it allows jekyll to configure some variables.
---
backend:
  name: git-gateway
  branch: admin # Branch to update (master by default)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

# publish_mode: editorial_workflow

display_url: {{ site.url }}

media_folder: "img/uploads/{{ site.time | date: "%Y" }}" # Folder where user uploaded files should go

slug:
  encoding: "ascii"
  clean_accents: true

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    label_singular: "Post" # singular label for certain elements in the editor; defaults to the value of label
    description: >
      The description is a great place for tone setting, high level information, and editing
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    delete: false # false prevents users from deleting items in a collection; defaults to true
    slug: "{% raw %}{{year}}-{{month}}-{{day}}-{{slug}}{% endraw %}"

    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "Comma separated tags. eg : tag one, tag two, other"}

      - {label: "Published Date", name: "pubdate", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}


  - name: "event"
    label: "Events"
    label_singular: "Event"
    folder: "_events"
    create: true
    slug: "{% raw %}{{year}}-{{month}}-{{day}}-{{slug}}{% endraw %}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "Comma separated tags. eg : tag one, tag two, other"}

      - {label: "Start Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "End Date", name: "end_date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      -
        label: "Contact"
        name: "contact"
        widget: "string"
      -
        label: "Url"
        name: "url"
        widget: "string"
